### ISSUE TITLE
How to open a local file with script?

### ISSUE THREAD

**Issue by EvgenyK-SO** [ladybug-tools/spider-gbxml-tools#22]
Currently we have a C# Revit application which does the following:
1. Exports Revit model to gbXML file, 
2. Makes some fixes
3. Starts FZK Viewer to review the model quality.

Now I want to replace FZK with Spider. Sorry, I am not a programmer, but know some basics. Please suggest how can I open a local gbXML file in the Spider viewer automatically?

Thank you.

**Comment by theo-armour** [comment]
@EK-CEL 

Click the question mark

![image](https://user-images.githubusercontent.com/547626/52757983-7338c180-2fbb-11e9-9025-cfc12e1d98e5.png)

Clicking should take you to this file:

https://www.ladybug.tools/spider-gbxml-tools/#sandbox/spider-gbxml-text-parser/r10/lib/file-open.md

The explanations are complicated but once you get the idea not difficult to put into your workflow

Please have a look at the text and help us make the concepts clearer and easier to get going.

Once we get going on this, I will move the file to a more up to date location.

**Comment by EvgenyK-SO** [comment]
@theo-armour 
I try to follow the instruction:
> Copy and paste a hashmark('#') followed by a file URI to the end of the link to gbXML Viewer in the address bar of your browser
> See Wikipedia [File URI Scheme]() https://en.wikipedia.org/wiki/File_URI_scheme )

I guess my link should be like this:
https://www.ladybug.tools/spider-gbxml-tools/spider-gbxml-viewer/r15/spider-gbxml-viewer15.html#file:///C:/Temp/18330.1-M19.xml

I tried to put the file to our Intranet:
https://www.ladybug.tools/spider-gbxml-tools/spider-gbxml-viewer/r15/spider-gbxml-viewer15.html#http://celoldintranet/departments/cad/video/test.xml

Nothing works for me with Chrome. Any suggestion? Thank you.

**Comment by theo-armour** [comment]
@EK-CEL @mdengusiak 

My bad. I left out the necessary magic trick. 😢 

Please see the updated version of this file. Also note new location.

[Opening and loading files with gbXML Viewer]( https://www.ladybug.tools/spider/#pages/file-open.md)

This release of the file has a new section you should look at titled 'Special note on using local files'.

All of this is a little bit complex. Please do help me to get the description of the process to get going as easy possible to read and act on. When you get these methods going you can save a huge number of clicks and keystrokes.

**Comment by EvgenyK-SO** [comment]
@theo-armour 

The instruction is good enough to understand and follow.


May be I am stupid, but after following your instructions I still cannot make it working.
Should this work?
![image](https://user-images.githubusercontent.com/39136340/53374148-889bdd00-3925-11e9-93b6-846923be4942.png)
I input *file:///C:/Temp/zz.xml* into address line and browser (Chrome or Firefox) opens the file, but the address doesn't work: 
https://www.ladybug.tools/spider-gbxml-tools/spider-gbxml-viewer/r15/spider-gbxml-viewer15.html#file:///C:/Temp/zz.xml

What am I doing wrong?
Thank you.

**Comment by theo-armour** [comment]
@EK-CEL 

I have added three new items to the FAQ. I hope these help.

## https://www.ladybug.tools/spider/#pages/file-open.md

**Comment by EvgenyK-SO** [comment]
@theo-armour 
Thank you for the FAQ update. It clarifies something.
I think that no need to input the file name in format *file:///*. The script converts the original file name correctly:
![image](https://user-images.githubusercontent.com/39136340/53426329-c5fb7b80-39b4-11e9-87c0-745f829b152b.png)



Unfortunately the picture indicates that I cannot open the file, even the Chrome is started as required:
![image](https://user-images.githubusercontent.com/39136340/53426185-82087680-39b4-11e9-9b96-08e934cbf310.png)

 
(I gonna cry) :-)

**Comment by theo-armour** [comment]
@EK-CEL 

> (I gonna cry) :-)

Me too. I reset all my browser setting to default and now I also can't load local files from Maevia running on GitHub - though I can load local files when Maevia is launched from my computer.

Anyway, it's time to rethink the workflow because it's all getting too complicated. 😞 

The objective is to minimize clicks and keystrokes. We want to be able to open a file using the file dialog box. go looking around for a file, make some changes, save it and then reload the file. But on this last step we don't want to go through the whole file dialog thing again

## [Spider gbXML Viewer 'Maevia' R15.23]( https://www.ladybug.tools/spider-gbxml-tools/spider-gbxml-viewer )

![image](https://user-images.githubusercontent.com/547626/53473025-3094d180-3a1e-11e9-97ec-bbb766f65acd.png)

It needs error checking, it needs to work with drag and drop.

What else does this feature need. Remember file used in a previous session (might be tricky to do)?

***

Re-reading your original request, the above is nice but does not solve your problem

So I will build a small HTML file of the Viewer that you can download. Running on your machine, this file should be able to access any local file. fingers crossed

**Comment by theo-armour** [comment]
@EK-CEL 

# Spider gbXML Viewer 'Maevia' Local

## Local version: https://www.ladybug.tools/spider-gbxml-tools/spider-gbxml-viewer/r15/spider-gbxml-viewer15-local.html


Download this file ( Chrome context menu > 'Save link as...' ) to your desktop or wherever, follow guidelines for loading local files here [Opening and loading files with gbXML Viewer]( https://www.ladybug.tools/spider/#pages/file-open.md ) in order to embed the Viewer in a local workflow and avoid CORS issues.

**Comment by EvgenyK-SO** [comment]
@theo-armour 
It works! Thank you very much!
BTW it accepts model file path in "standard" format, i.e. c:\Temp\zz.xml. There is no need using *file:///* prefix. Please update the FAQ article.

**Comment by theo-armour** [comment]
@EK-CEL 

> It works! Thank you very much!

Yay, at last! We can stop crying now.

I'm sure there will be issues - and ways we can make the workflow even smoother. So do keep me pushing us for improvements.

> BTW it accepts model file path in "standard" format, i.e. c:\Temp\zz.xml. There is no need using file:/// prefix. 

Yes, thank you for showing me this!

> Please update the FAQ article.

Will do. I will also add details about the local file and it's usage.

**Comment by mdengusiak** [comment]
I hope this works now. We moving on and I am closing this now.
