### ISSUE TITLE
Spider_gbXML_Viewer_R15.3: Air Wall Fix

### ISSUE THREAD

**Issue by mdengusiak** [ladybug-tools/spider-gbxml-tools#24]
As discussed moved to separate issue  `Issue `- Fix Air?

We already identified before _Air_ cases:
We have to distinguish between _Air_ and _Shade+Air_.

If we have Shade **and** there is parallel surface with air: this is quite easy.
1. take from front shade CADObjectID
2. check if Air have the same space for adjacent space 1 and 2
if yes modify delete one surface and use following data: 
-  change `type ` to ExternalWall or Roof or Floor 
     - Type can aslo be recognized from CADObjectID as I can see you use Revit so it key words will be...`Basic Wall:` `Basic Roof:` `Floor:`
- add `CADObjectID `from Shade
- add `adjacent space 1` from Air

I prefer to keep `Shade `and delete `Air `as shade is fully enclosed from outside. 
<img src="https://user-images.githubusercontent.com/26113670/52695923-98024a00-2f65-11e9-85bd-668efdc223ab.png" width=480>
<img src="https://user-images.githubusercontent.com/26113670/52695930-9df82b00-2f65-11e9-9bb4-91fbc6359d4c.png" width=480>

**Comment by EvgenyK-SO** [comment]
Just copying my comment from previous thread.

------------
> ...delete `Air `as shade is fully enclosed from outside.

For this particular situation the Air surface should be changed for Exterior Wall surface. Do you plan to delete all Air surfaces from the model.
I believe Air surfaces should be kept, because it is information. Imagine we "compress" a 24 megapixel picture to 100 KB. Most of information get lost and cannot be recovered. Same about Air surfaces. They potentially can be used later, not for energy calculations, but for CFD, for example. So please keep Air surfaces unless they are harmful. 

> I prefer to keep `Shade `

I don't think it is correct. If we found that the Air and Shade surfaces work together then we fix Air surface. The Shade should not appear on top of it, so we delete it.
![image](https://user-images.githubusercontent.com/39136340/52717582-6d1cf380-2f6f-11e9-8644-41f82367fabc.png)

**Comment by mdengusiak** [comment]
@EK-CEL 
ok I moved this to separate issue... however I would like to clarify my suggested approach 

> I don't think it is correct. If we found that the Air and Shade surfaces work together then we fix Air surface. The Shade should not appear on top of it, so we delete it.

The only way of truly fix it is to run geometrical adjustment trim/expand surfaces. This is separate subject so lets start to get solution that exist in Spider. If you delete Shade and fix Air your shape will cause lots of issues as you will have lots of tiny surfaces. Of course depends what is purpose and which tool you are using. Model from Revit is exported as gbXML this means that we have only center line for building elements.  If I will use for Energy simulation and ie TAS, Solar-Computer where I apply real thickness for all elements ie. External Wall =  600mm. When it run expand  expand tiny elements  (see with red arrow) this will cause lots of issues. So I prefer to pull data from Air and assign to shade element and transform shade element into  Exterior Wall as wall next to it. In this case I have perfect and neat model. If we do ie. CFD and we want to capture all details then is different story but in this case I can see straight away this is not detail from Revit just error that was exported during gbXML export process. 

![image](https://user-images.githubusercontent.com/14005893/52744956-dc2d3300-2fd5-11e9-89d1-4eaaddc59ef4.png)


> For this particular situation the Air surface should be changed for Exterior Wall surface. Do you plan to delete all Air surfaces from the model.
> I believe Air surfaces should be kept, because it is information. Imagine we "compress" a 24 megapixel picture to 100 KB. Most of information get lost and cannot be recovered. Same about Air surfaces. They potentially can be used later, not for energy calculations, but for CFD, for example. So please keep Air surfaces unless they are harmful.
As above agreed it should be  Exterior Wall, it will be recovered when we do proper merge of surface data. Normally I only keep real air surfaces that are big area represented fur Air-Wall or Air-Floor. In face I personally prefer to call wall, floor air and have full control over genuine elements and distinguish from errors - Air. 

However everyone has different workflows and we need to find solution that is flexible enough for help fix all models. So we need lots of flexibility for selection and ability to easily modify everything.  :)

**Comment by mdengusiak** [comment]
@EK-CEL ok to avoid confusion I hidden discussion on other thread so we have all in one place

**Comment by EvgenyK-SO** [comment]
> transform shade element into Exterior Wall as wall next to it.

If so, I totally agree to remove Air surfaces related to the Shade.

**Comment by theo-armour** [comment]
@mdengusiak @EK-CEL 

Maevia R15.14 has a new Edit Menu panel: 'Air Surface Type Editor'

This panel is a work-in-progress - still incomplete and at an early stage. But some of the bttons work and you can visualize the thought processes behind the code. Future versions will combine all the vuttons into one.

The objective is to identify all Air surfaces that on the exterior of the model. In future versions this could also check all other interior type surfaces, but let us start with Air surfaces as these seem to be the most issues with these.

BTW, this release contains a number of fixes throughout. You can identify the changes by clicking the many '?'. Please do check these as well and report faulty grammar and spelling etc.

**Comment by EvgenyK-SO** [comment]
@mdengusiak @theo-armour 
Here is another sample file for experiments. This is what we typically have.
Architectural model is never perfect and we modify it in some degree, but our mechanical designers are not architects and they cannot know building envelope design tools in Revit well. Also time for tackling the model is limited. So with our best efforts we can afford for fixing model we still have not a perfect model.
Another thing is that we specify spaces as we need for design. They can be broken for subdivisions for better gbXML, but I don't think it is a good idea. So this "ready for calculations" model still has problems:
![image](https://user-images.githubusercontent.com/39136340/52793385-9b680500-303b-11e9-883a-51201f8915ca.png)

This model was used for calculations. It was imported into HAP and the indicated problems fixed manually.

**Comment by theo-armour** [comment]
@EK-CEL 

Thanks for send this model. Here it is rendered with the Maevia after an Air surface Check

![image](https://user-images.githubusercontent.com/547626/52826745-f9fea480-3076-11e9-96f7-0cd8269777c6.png)

BTW, you will notice that a number of the surfaces are skewed. This is because some of the coordinates of the building run to 7 places to left of decimal and 3 to right. After all the matrix multiplications and still wanting to run fast in a browser, mathematical precision and  visual cleanliness are taking a hit with this model.

              <CartesianPoint>
                <Coordinate>604317.5</Coordinate>
                <Coordinate>4834885</Coordinate>
                <Coordinate>209.765</Coordinate>
              </CartesianPoint>

Future releases of Maevia could fix this issue if wanted. In the mean time would it be possible to get a version of the model situated closer to the origin? Also can we use this model as a public test case?

BTW, the effort to do even better error checking, selecting multiple surfaces and push-one-button-to-fix will continue.

**Comment by michaldengusiak** [comment]
@EK-CEL 
Please review in your Revit model: Project Set Point to be 0,0,0, before you export gbXML
![image](https://user-images.githubusercontent.com/26113670/52842125-0bd35c80-30f6-11e9-96ee-949ebb69292d.png)

**Comment by EvgenyK-SO** [comment]
@theo-armour 
> Here it is rendered with the Maevia after an Air surface Check

The indicated problems still are there. :( 

> Future releases of Maevia could fix this issue if wanted.

Yes! Please!

**Comment by theo-armour** [comment]
@EK-CEL @mdengusiak 

Maevia R15.18

![image](https://user-images.githubusercontent.com/547626/53208504-e362cb00-35eb-11e9-9ffc-0c20a459901e.png)

Better detection of air surfaces on exterior

But:
* No detection of interior walls appearing on exterior of model
* No detection of exterior walls that should b shade

Now that we have the beginning of reasonable interior/exterior identification. The two above issues can (and shall) be tackled

My only question is just the bigger one for the moment: What needs to be finished so that Maevia R15 can become the stable release?

**Comment by theo-armour** [comment]
@EK-CEL 

This issue is now over my brain capacity to handle.   ;- )

I think most aspects are being covered else where.

Please close this issue if you feel it's OK. And please do start new issues on any aspects you feel are still unsolved.

**Comment by EvgenyK-SO** [comment]
@theo-armour 
Which issue:
1. Automatic fix for Air surfaces?
2. Specific problem with the last sample model?

**Comment by theo-armour** [comment]
Spider_gbXML_Viewer_R15.3: Air Wall Fix

https://github.com/ladybug-tools/spider-gbxml-tools/issues/24

**Comment by EvgenyK-SO** [comment]
@theo-armour 

I didn't believe the problem can be fixed automatically. Although I hoped for magic. :)
@mdengusiak created the issue. Should we ask him to close it?

**Comment by mdengusiak** [comment]
This is approach we try to implement now in our BHoM gbXML export. I believe would be powerful to have as well and once you export  gbXML from Revit using BHoM.
This however requires geometry understanding and ability to recognize parallel surfaces close to each other. I will have call with Theo to check if we have already have this capability or we need to postpone this for next edition.

**Comment by theo-armour** [comment]
@mdengusiak @EK-CEL 

The 'Air Surface Type Editor' in the Edit menu is beginning to take shape, It's doing a fairly good job of finding any intersection cast from a normal of a surface. It can already isolate all internal Air surfaces, all external horizontal Air surfaces and all external vertical Air surfaces. Future revisions will work with any surface type. And future revisions should also be able to identify surface that have zero or very little distance in between.

Someone should start some new issues with use cases that I can develop for. Such as identify all external Air surfaces that should be slabs, all interior surfaces that are on the outside of the building, all overlapping surfaces etc

**Comment by mdengusiak** [comment]
ok agreed...
we will log each "problematic" item as small issue with sample so easy to debug and solve together :)
