### ISSUE TITLE
Spider gbXML Viewer 'Maevia' R15.23: Issue with surfaces Panel-276 and Panel-279

### ISSUE THREAD

**Issue by mdengusiak** [ladybug-tools/spider-gbxml-tools#30]
I have broken file that does not import into simulation tool,
Panel-276 and Panel-279 are problematic. 

I can see also problem in ver R12.34 as surface is not displaying but it does show in R15.23 without any error. We need to find what is problem with these surfaces and log this under issues in 'Maevia' we know what is problem inside gbXML.

![image](https://user-images.githubusercontent.com/14005893/53491932-7e95ed80-3a8f-11e9-9faf-aab9f1fdddd5.png)

![image](https://user-images.githubusercontent.com/14005893/53491977-9ec5ac80-3a8f-11e9-9006-27f662598b23.png)

test file:
[BHoMgbXMLrevitSAM_TAS.zip](https://github.com/ladybug-tools/spider-gbxml-tools/files/2910355/BHoMgbXMLrevitSAM_TAS.zip)

**Comment by theo-armour** [comment]
@mdengusiak 

I have had a quick look at the XML file and at the display in the viewers. It seems to me that the issue is that the mullions are just 6 mm. The surface is 4.5 high. The opening is 4.488 high. 

Since R12 cuts holes in surfaces, so there is nothing left to see in R12 and becomes almost invisible. R15 draws the outline of an opening but does not yet cut holes - so you see the full surface.

I think the model is OK and provides a good test case for how should we build a viewer that helps you identify and handle surfaces with near full-size openings.

**Comment by mdengusiak** [comment]
@theo-armour 
OK I manage to isolate issue and here is just two zone model with problem
[BHoMgbXMLrevit2zones_TAS.zip](https://github.com/ladybug-tools/spider-gbxml-tools/files/2914145/BHoMgbXMLrevit2zones_TAS.zip)
What it is actually Curtain Wall System Panel from two different walls have same geometry and this is wrong in XML. Would be good to get some check and highlight under issue.  

here are images:
https://github.com/BHoM/Revit_Toolkit/issues/248

**Comment by mdengusiak** [comment]
to be fix by Fixed
